- hosts: all
  become: yes
  become_user: root
  roles:
    - { role: cli }
    - { role: gui }
    - { role: openstack }

- hosts: all
  vars:
  - ansible_ssh_user: root
  roles:
    - { role: lockdown }
