- hosts: all
  vars:
  - upgrade_to_sid: no
  become: yes
  become_user: root
  roles:
    - { role: cli }
    - { role: gui }

- hosts: all
  vars:
  - ansible_ssh_user: root
  roles:
    - { role: lockdown }
