- name: Adds google chrome repo
  copy: src=google-chrome.list
        dest=/etc/apt/sources.list.d/google-chrome.list
        owner=root
        group=root
        mode=0644

- name: Import google's key
command: bash -c "wget -q -O -
                  https://dl.google.com/linux/linux_signing_key.pub
                  | sudo apt-key add -"

- name: Update to apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Installs necessary packages
  apt: pkg={{ item }} state=latest
  with_items:
    - feh
    - google-chrome-stable
    - rxvt-unicode-256color
    - slim
    - sxiv
    - xcompmgr
    - xkbset
    - xmobar
    - xmonad
    - xscreensaver

- name: Assures config directory exists
  file: path=/home/{{ user }}/.config/ state=directory
  become: yes
  become_user: "{{ user }}"

- name: Installs wallpaper
  copy: src=wallpaper
        dest=/home/{{ user }}/.config/wallpaper
        owner={{ user }}
        group={{ user }}
        mode=0640
  become: yes
  become_user: "{{ user }}"

- name: Deploys xmonad
  git: repo=https://github.com/CrashenX/xmonad.git dest=~/src/xmonad/
  become: yes
  become_user: "{{ user }}"

- name: Deploys bashrc additions for xmonad
  get_url: url=https://raw.githubusercontent.com/CrashenX/xmonad/master/bashrc
           dest=~/.bashrc_{{ user }}_xmonad
           owner={{ user }}
           group={{ user }}
           mode=0640
  become: yes
  become_user: "{{ user }}"

- name: Configures user bashrc to use xmonad additions
  lineinfile: dest=~/.bashrc_{{ user }}
              line=". ~/.bashrc_{{ user }}_xmonad"
              regexp="^. ~/.bashrc_{{ item.user }}_xmoand"
  become: yes
  become_user: "{{ user }}"

- name: Installs xmonad configs
  command: ~/src/xmonad/install
  become: yes
  become_user: "{{ user }}"

- name: Restricts access to unprivileged user files
  file: path=/home/{{ user }} state=directory recurse=yes mode="o-rwx"
