- name: Creates unprivileged user
  user: name={{ user }}
        password={{ password }}
        groups="sudo"
        generate_ssh_key=yes
        ssh_key_bits=4096
        ssh_key_file=.ssh/id_rsa
        shell=/bin/bash

- name: Adds authorized key
  authorized_key: user={{ item }}
                  key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  with_items:
    - root
    - "{{ user }}"

- name: Locks root password
  command: passwd -l root

- name: Disallows ssh password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Updates current dist
  apt: update_cache=yes upgrade=dist

- name: Updates apt sources list
  copy: src=sources.list
        dest=/etc/apt/sources.list
        owner=root
        group=root
        mode=0644

- name: Updates to Sid
  apt: update_cache=yes upgrade=dist

- name: Installs packages
  apt: pkg={{ item }} state=latest
  with_items:
    - fail2ban
    - ufw
    - unattended-upgrades
    - vim
    - virtualbox-guest-*

- name: Sets up ufw
  command: ufw allow 22/tcp

- name: Enables ufw
  command: ufw --force enable

- name: Restricts access to unprivileged user files
  file: path=/home/{{ user }} state=directory recurse=yes mode="o-rwx"
