- name: Installs necessary packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - realpath
    - screen
    - vim-gtk

- name: Adds github to known_hosts
  copy: src=github_rsa.pub
        dest=/home/{{ user }}/.ssh/known_hosts
        owner={{ user }}
        group={{ user }}
        mode=0640

- name: Deploys bashrc additions
  get_url: url=https://raw.githubusercontent.com/CrashenX/bashrc/master/bashrc
           dest={{ item.basedir }}/.bashrc_{{ item.user }}
           owner={{ item.user }}
           group={{ item.user }}
           mode=0640
  become: yes
  become_user: "{{ item.user }}"
  with_items:
    - { user: 'root', basedir: '/root' }
    - { user: "{{ user }}", basedir: "/home/{{ user }}" }

- name: Configures bashrc to use additions
  lineinfile: dest={{ item.basedir }}/.bashrc
              line=". {{ item.basedir }}/.bashrc_{{ item.user }}"
              regexp="^. {{ item.basedir }}/.bashrc_{{ item.user }}"
  become: yes
  become_user: "{{ item.user }}"
  with_items:
    - { user: 'root', basedir: '/root' }
    - { user: "{{ user }}", basedir: "/home/{{ user }}" }

- name: Deploys vim config
  git: repo=ssh://git@github.com:CrashenX/vimrc.git
       dest=/home/{{ user }}/src/vimrc/
  become: yes
  become_user: "{{ user }}"

- name: Installs vim config
  command: /home/{{ user }}/src/vimrc/install
  become: yes
  become_user: "{{ user }}"

- name: Deploys screenrc
  get_url: url=https://raw.githubusercontent.com/CrashenX/screenrc/master/screenrc
           dest=/home/{{ user }}/.screenrc
           owner={{ user }}
           group={{ user }}
           mode=0640

- name: Restricts access to unprivileged user files
  file: path=/home/{{ user }} state=directory recurse=yes mode="o-rwx"
