- name: Update to apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Installs necessary packages
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - vim-gtk

- name: Adds github to known_hosts
  copy: src=github_rsa.pub
        dest=/home/{{ user }}/.ssh/known_hosts
        owner={{ user }}
        group={{ user }}
        mode=0640

- name: Deploys vim config
  git: repo=https://github.com/CrashenX/vimrc.git dest=~/src/vimrc/
  tags: deploy
  become: yes
  become_method: su
  become_user: "{{ user }}"

- name: Installs vim config
  command: ~/src/vimrc/install
  become: yes
  become_method: su
  become_user: "{{ user }}"

- name: Restricts access to unprivileged user files
  file: path=/home/{{ user }} state=directory recurse=yes mode="o-rwx"
